# Generated by Django 2.0.7 on 2018-08-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cedula',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
