# Generated by Django 2.0.7 on 2018-08-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180810_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cedula',
            field=models.CharField(blank=True, default='0000000000', max_length=13),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='codigo_externo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='movil',
            field=models.CharField(blank=True, default='11111111', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='propietario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, default='11111111', max_length=10),
        ),
    ]
