# Generated by Django 2.0.7 on 2018-07-24 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now=True)),
                ('fecha_invitacion', models.DateTimeField()),
                ('estado_invitacion', models.CharField(choices=[('Pendiente', 'P'), ('Realizado', 'R'), ('Cancelado', 'C')], max_length=1)),
                ('nombre_invitado', models.CharField(max_length=60)),
                ('apellido_invitado', models.CharField(max_length=60)),
                ('cedula_invitado', models.CharField(max_length=13)),
                ('tipo_invitacion', models.CharField(choices=[('SOCIAL', 'S'), ('TRABAJO', 'T'), ('PROVEEDORES', 'P')], max_length=1)),
                ('codigo_invitacion', models.CharField(max_length=128)),
                ('residente_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('edad', models.PositiveIntegerField()),
                ('cedula', models.CharField(max_length=13)),
                ('genero', models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F'), ('Otro', 'O')], max_length=1)),
                ('email', models.EmailField(max_length=60)),
                ('telefono', models.CharField(max_length=16)),
                ('movil', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
