# Generated by Django 2.0.7 on 2018-08-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F')], max_length=1),
        ),
    ]
