# Generated by Django 2.0.7 on 2018-09-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0002_auto_20180810_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='tipo_invitacion',
            field=models.CharField(choices=[('S', 'SOCIAL'), ('T', 'TRABAJO'), ('P', 'PROVEEDORES')], max_length=1),
        ),
    ]
