# Generated by Django 2.0.7 on 2018-09-06 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egate', '0003_auto_20180831_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='pk_user',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
