# Generated by Django 2.0.7 on 2018-09-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0004_invitado_pk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
