# Generated by Django 2.0.7 on 2018-09-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0008_invitado_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='dob',
            field=models.DateField(default='2018-09-01'),
            preserve_default=False,
        ),
    ]
