# Generated by Django 2.0.7 on 2018-09-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0009_invitado_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitado',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='edad',
        ),
    ]
