# Generated by Django 2.0.7 on 2018-09-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0010_auto_20180906_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='edad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
