# Generated by Django 2.0.7 on 2018-09-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0011_invitado_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitado',
            name='edad',
        ),
    ]
