# Generated by Django 2.0.7 on 2018-09-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0012_remove_invitado_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='dob',
            field=models.DateField(default=("2018-09-06")),
            preserve_default=False,
        ),
    ]
