# Generated by Django 2.0.7 on 2018-09-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0014_auto_20180908_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='movil',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
