# Generated by Django 2.0.7 on 2018-09-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0015_auto_20180908_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='save_contact',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
