# Generated by Django 2.0.7 on 2018-09-21 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egate', '0016_invitacion_save_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzana', models.CharField(max_length=10)),
                ('villa', models.CharField(max_length=10)),
                ('calle1', models.CharField(blank=True, max_length=80, null=True)),
                ('calle2', models.CharField(blank=True, max_length=80, null=True)),
                ('conjunto', models.CharField(max_length=80)),
                ('departamento', models.CharField(blank=True, max_length=10, null=True)),
                ('residente_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
