# Generated by Django 2.0.7 on 2018-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0018_invitacion_direccion_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_categoria', models.CharField(max_length=100)),
                ('estado_categoria', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='tipo_invitacion',
            field=models.CharField(choices=[('S', 'SOCIAL'), ('T', 'TRABAJO')], max_length=1),
        ),
    ]
