# Generated by Django 2.0.7 on 2018-10-07 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0019_auto_20181007_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_proveedor', models.CharField(max_length=100)),
                ('estado_proveedor', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], max_length=1)),
                ('direccion_proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('georeferencia_proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egate.CategoriaProveedores')),
            ],
        ),
    ]
