# Generated by Django 2.0.7 on 2018-10-07 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('egate', '0020_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizarProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now=True)),
                ('fecha_autorizacion', models.DateTimeField()),
                ('estado_autorizacion', models.CharField(choices=[('Pendiente', 'P'), ('Realizado', 'R'), ('Cancelado', 'C')], max_length=1)),
                ('codigo_invitacion', models.CharField(max_length=128)),
                ('direccion_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egate.Direccion')),
                ('nombre_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egate.Proveedores')),
                ('residente_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
