# Generated by Django 2.0.7 on 2018-10-07 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0021_autorizarproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizarproveedor',
            name='nombres_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='egate.CategoriaProveedores'),
            preserve_default=False,
        ),
    ]
