# Generated by Django 2.0.7 on 2018-10-08 05:04

from django.db import migrations, models
import egate.models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0022_autorizarproveedor_nombres_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='cedula',
            field=models.CharField(blank=True, default=egate.models.Invitado.cedula_default, max_length=13),
        ),
    ]
