# Generated by Django 2.0.7 on 2018-11-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egate', '0024_auto_20181008_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizarproveedor',
            name='estado_autorizacion',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Realizado', 'R'), ('Cancelado', 'C'), ('Vencido', 'V')], max_length=1),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='estado_invitacion',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Realizado', 'R'), ('Cancelado', 'C'), ('Vencido', 'V')], max_length=1),
        ),
    ]
